https://www.alphavantage.co/query?function=DIGITAL_CURRENCY_DAILY&symbol=ETH&market=CHF&apikey=3EBLV8FMHCBNU0JI
https://www.alphavantage.co/query?function=CRYPTO_RATING&symbol=ETH&apikey=3EBLV8FMHCBNU0JI
https://www.alphavantage.co/query?function=CURRENCY_EXCHANGE_RATE&from_currency=ETH&to_currency=EUR&apikey=3EBLV8FMHCBNU0JI
