
http://localhost:8000/api/exchangeRate/ETH/CHF/refresh

###

http://localhost:8000/api/exchangeRate/ETH/CHF

###

http://localhost:8000/api/exchangeRate/ETH/CHF/2021-02-05T15:22:37.000Z

###

http://localhost:8000/api/exchangeRate/ETH/CHF/2021-02-05T10:00:00.000Z/2021-02-05T22:00:00.000Z

###

https://www.alphavantage.co/query?function=CURRENCY_EXCHANGE_RATE&from_currency=ETH&to_currency=CHF&apikey=3EBLV8FMHCBNU0JI

###

https://www.alphavantage.co/query?function=DIGITAL_CURRENCY_DAILY&symbol=ETH&market=CHF&apikey=3EBLV8FMHCBNU0JI

###

https://www.alphavantage.co/query?function=DIGITAL_CURRENCY_WEEKLY&symbol=ETH&market=CHF&apikey=3EBLV8FMHCBNU0JI

###

http://localhost:8000/api/portfolio/601abdd67dcd284857ebc044

###

http://localhost:8000/api/portfolio

###

https://www.alphavantage.co/query?function=CRYPTO_RATING&symbol=ETH&apikey=3EBLV8FMHCBNU0JI
